In [2]:
from aocd import get_data

YEAR = 2022
DAY = 12

dat = get_data(day=DAY,year=YEAR)

with open('input/12','w') as f:
    f.write(dat)



f.close()



In [3]:
import numpy as np
with open('input/12') as f:
    dat = np.array([list(map(ord,list(i))) for i in f.read().split('\n')])
# S = 83, E = 69
print(dat)

[[97 98 99 ... 97 97 97]
 [97 98 99 ... 97 97 97]
 [97 98 99 ... 97 97 97]
 ...
 [97 98 99 ... 97 97 97]
 [97 98 99 ... 97 97 97]
 [97 98 99 ... 97 97 97]]


In [4]:
class Cell:
    def __init__(self, row, col):
        self.value = 0
        self.row = row
        self.col = col
        self.neighbors = []
        self.foundStep = 999 # for search
    

    def add_neighbor(self, cell):
        
        self.neighbors.append(cell)
    
    def __repr__(self) -> str:
        s = 'Row: ' + str(self.row) + ' Col: '+ str(self.col) + ' val: ' +chr(self.value) + '\n'
        return s
    
        

In [5]:
class CellMap:
    def __init__(self, rows, cols):
        self.rows = rows
        self.cols = cols
        self.grid = [[Cell(row, col) for col in range(cols)] for row in range(rows)]
    
    def connect(self):
        for row in range(self.rows):
            for col in range(self.cols):
                cell = self.grid[row][col]
                if row > 0:
                    cell.add_neighbor(self.grid[row - 1][col])
                if row < self.rows - 1:
                    cell.add_neighbor(self.grid[row + 1][col])
                if col > 0:
                    cell.add_neighbor(self.grid[row][col - 1])
                if col < self.cols - 1:
                    cell.add_neighbor(self.grid[row][col + 1])
    def __getitem__(self, index):
        return self.grid[index]

In [6]:
ix = dat.shape[0]
iy = dat.shape[1]

A = CellMap(ix,iy)

for i in range(ix):
    for j in range(iy):
        # print(dat[i][j])
        A[i][j].value = dat[i][j]
        if (dat[i][j] == ord('E')):
            A[i][j].value = ord('{')
        if (dat[i][j] == ord('S')):
            starter = A[i][j]
            A[i][j].foundStep = 0
            A[i][j].value = ord('`') #just before 'a'

print(dat.shape)

(41, 101)


In [7]:
A.connect()
searchStack = []
searchStack.extend(starter.neighbors)   

while len(searchStack) > 0:
    s = searchStack.pop()
    # print(f'current item: {s}, foundStep: {s.foundStep}')
    # print(f'neighbors: ')
    for n in s.neighbors: #check all 4 neighbors
        if(((s.value- n.value) < 2)):
            s.foundStep = min(s.foundStep, n.foundStep +1)
        # print(f'new value: {s.foundStep}')

    for n in s.neighbors:
        if( ((n.value- s.value) < 2)):
            if n.foundStep > s.foundStep +1:
                # print(f'appending: {n}, with current fs of {n.foundStep}')
                searchStack.append(n)
    # print(s.foundStep)
    
for i in range(ix):
        for j in range(iy):        
        # print('\t'.join([str(A[i][j].foundStep) for j in range(iy)]))
                if(A[i][j].value == ord('{')):
                        print(f'Sol 1: {A[i][j].foundStep}')

Sol 1: 361


In [8]:
# Part 2 init cell

ix = dat.shape[0]
iy = dat.shape[1]

A = CellMap(ix,iy)

for i in range(ix):
    for j in range(iy):
        # print(dat[i][j])
        A[i][j].value = dat[i][j]
        if (dat[i][j] == ord('E')):
            A[i][j].value = ord('{')
            #now this is the starting point
            starter = A[i][j]
            A[i][j].foundStep = 0
        if (dat[i][j] == ord('S')):
            A[i][j].value = ord('`') 

print(dat.shape)


(41, 101)


In [9]:
# part 2 solve
A.connect()
searchStack = []
searchStack.extend(starter.neighbors)   

while len(searchStack) > 0:
    s = searchStack.pop()
    # print(f'current item: {s}, foundStep: {s.foundStep}')
    # print(f'neighbors: ')
    for n in s.neighbors: #check all 4 neighbors
        if(((n.value- s.value) < 2)):  #n is neighbor, s is cell
            s.foundStep = min(s.foundStep, n.foundStep +1)
        # print(f'new value: {s.foundStep}')

    for n in s.neighbors:
        if( ((s.value- n.value) < 2)):
            if n.foundStep > s.foundStep +1:
                # print(f'appending: {n}, with current fs of {n.foundStep}')
                searchStack.append(n)
    # print(s.foundStep)

# for i in range(ix):
#         # for j in range(iy):        
#         print('\t'.join([str(A[i][j].foundStep) for j in range(iy)]))
#                 # if(A[i][j].value == ord('{')):
#                 #         print(f'Sol 1: {A[i][j].foundStep}')

sols = []
for i in range(ix):
        for j in range(iy):        
        # print('\t'.join([str(A[i][j].foundStep) for j in range(iy)]))
            if(A[i][j].value == ord('a')):
                sols.append(A[i][j].foundStep)
print(f'problem 2: {min(sols)}')

problem 2: 354
