In [141]:

print(True != False)

True


In [142]:
from aocd import get_data

YEAR = 2022
DAY = 18

dat = get_data(day=DAY,year=YEAR)

with open('input/18','w') as f:
    f.write(dat)

f.close()

In [143]:
with open('input/18') as f:
    dat =  [[int(j) for j in i.split(',')] for i in f.read().split('\n')]


In [144]:
maxX = 0
maxY = 0
maxZ = 0

for x,y,z in dat:
    maxX = max(x,maxX)
    maxY = max(y,maxY)
    maxZ = max(z,maxZ)

maxX +=1
maxY +=1
maxZ +=1
print(maxX, maxY, maxZ)

21 22 22


In [145]:
import numpy as np

A = np.zeros((maxX,maxY,maxZ))
for x,y,z in dat:
    A[x,y,z] = 1
A = np.pad(A,1)
print(np.shape(A))
print(maxX)

(23, 24, 24)
21


In [146]:
def countDiff(L):
    c = 0
    for i in range(len(L)-1):
        c += (L[i]!=L[i+1])
    return c

sides = 0
for i in range(1,maxX+1):
    for j in range(1,maxY +1):
        sides +=(countDiff(A[i,j,:]))

for i in range(1,maxX+1):
    for k in range(1,maxZ +1):
        sides +=(countDiff(A[i,:,k]))

for j in range(1,maxY+1):
    for k in range(1,maxZ +1):
        sides +=(countDiff(A[:,j,k]))

print(sides)

4482


In [147]:
outsideStack = []

outsideStack.append([1,1,1])

while len(outsideStack)!=0:
    s = outsideStack.pop()
    A[s[0],s[1],s[2]] = 3

    if(s[0] > 0):
        if(A[s[0]-1,s[1],s[2]] == 0):
            outsideStack.append([s[0]-1,s[1],s[2]])

    if(s[0] < maxX+1):
        if(A[s[0]+1,s[1],s[2]] == 0):
            outsideStack.append([s[0]+1,s[1],s[2]])

    if(s[1] > 0):
        if(A[s[0],s[1]-1,s[2]] == 0):
            outsideStack.append([s[0],s[1]-1,s[2]])

    if(s[1] < maxY+1):
        if(A[s[0],s[1]+1,s[2]] == 0):
            outsideStack.append([s[0],s[1]+1,s[2]])

    if(s[2] > 0):
        if(A[s[0],s[1],s[2]-1] == 0):
            outsideStack.append([s[0],s[1],s[2]-1])

    if(s[2] < maxZ+1):
        if(A[s[0],s[1],s[2]+1] == 0):
            outsideStack.append([s[0],s[1],s[2]+1])



In [148]:
def countDiffpart2(L):
    c = 0
    for i in range(len(L)-1):
        c += (abs(L[i]-L[i+1]) ==2)
    return c

sides = 0
for i in range(1,maxX+1):
    for j in range(1,maxY +1):
        sides +=(countDiffpart2(A[i,j,:]))

for i in range(1,maxX+1):
    for k in range(1,maxZ +1):
        sides +=(countDiffpart2(A[i,:,k]))

for j in range(1,maxY+1):
    for k in range(1,maxZ +1):
        sides +=(countDiffpart2(A[:,j,k]))
print(sides)

print(A)

2576
[[[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  ...
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  ...
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  ...
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 ...

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  ...
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  ...
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]

 [[3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  ...
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]
  [3. 3. 3. ... 3. 3. 3.]]]
