In [66]:
from aocd import get_data

YEAR = 2022
DAY = 22

dat = get_data(day=DAY,year=YEAR)

with open('input/22','w') as f:
    f.write(dat)

f.close()

In [67]:
with open('input/22') as f:
    dat =  f.read().split('\n')

import regex as re
comm  = dat[-1]
dat = dat[:-2]
X = max([len(l) for l  in dat])
Y = len(dat)
print(X,Y)

16 12


In [68]:
import numpy as np
A = np.zeros((Y,X),dtype=int)
# print(A)

for lIdx, l in enumerate(dat):
    s = l.lstrip(' ')
    spaces = len(l) - len(s)
    for i in range(spaces,spaces + len(s)):
        A[lIdx][i] = 1 if( l[i] == '.') else -1
print(A)

[[ 0  0  0  0  0  0  0  0  1  1  1 -1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1 -1  1  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 -1  1  1  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  1  1  0  0  0  0]
 [ 1  1  1 -1  1  1  1  1  1  1  1 -1  0  0  0  0]
 [ 1  1  1  1  1  1  1  1 -1  1  1  1  0  0  0  0]
 [ 1  1 -1  1  1  1  1 -1  1  1  1  1  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1 -1  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  1 -1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  1  1  1  1  1 -1  1  1]
 [ 0  0  0  0  0  0  0  0  1 -1  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  0  1  1  1  1  1  1 -1  1]]


In [74]:
import math
def moveAhead(A,pos,dir,move):
    if(dir ==0):  #right
        l = A[pos[0],:]
        # print(f'l: {l} \npos{pos}, move: {move}')
        pos[1] = moveDir(l,pos[1],move)
        return pos
        # print(pos)
    if(dir ==2):  # left
        l = A[pos[0],:]
        # print(l)
        l = l[::-1]
        # print(l)
        # print(f'l: {l} \npos{pos}, move: {move}')
        postmp= moveDir(l,len(l) - pos[1] - 1,move)
        pos[1] = len(l) - postmp -1
        return pos
        # print(pos)
    if(dir == 1): # up
        # print(A[:pos[0],pos[1]])
        l = A[:,pos[1]]
        l = l[::-1]
        # print(f'l: {l} \npos{pos}, move: {move}')
        postmp= moveDir(l,len(l) - pos[0] -1,move)
        pos[0] = len(l) - postmp -1
        return pos
        # print(pos)
    if(dir == 3): # down
        # print(A[pos[0]+1:,pos[1]])
        l = A[:,pos[1]]
        # print(f'l: {l} \npos{pos}, move: {move}')
        pos[0] = moveDir(l,pos[0],move)
        return pos
        # print(pos)
def moveDir(l,pos,move):
        # np.where(l!=0)
        s = l[np.where(l!=0)]
        # print(f'pos: {pos}')
        # print(f'l: {l}')
        # print(f's: {s}')
        spos =pos -  np.where(l!=0)[0][0]
        # print(f'spos: {spos}')
        # print(f'move: {move}')
        # print(f'npweher: {np.where(l!=0)[0][0]}')
        # print(f'spos after move: {(spos + move)%len(s)}')
        loopCount = math.floor((spos + move) /len(s))
        stile = np.tile(s,loopCount+1)
        # print(f'loopcount: {loopCount}')
        # print(f'new l: {stile}')
        # print(f'stile until move: {stile[spos+1:(spos + move+1)]}')
        if(len(np.where(stile[spos+1:spos + move+1]==-1)[0]) ==0):
            # print('no -1s in current dir')
            # print(f'final pos: {(spos + move )%len(s) +  np.where(l!=0)[0][0]}')
            return (spos + move )%len(s) +  np.where(l!=0)[0][0]
        else:
            # print('there is -1 in dir')
            #there is a -1 is the move direction
            # print((spos + np.where(stile[spos+1:spos + move+1]==-1)[0][0])%len(s) + spos)
            # print(f'final pos: {(spos+ np.where(stile[spos+1:spos + move+1]==-1)[0][0])%len(s) +np.where(l!=0)[0][0]}')
            return (spos+ np.where(stile[spos+1:spos + move+1]==-1)[0][0])%len(s) +np.where(l!=0)[0][0]


In [76]:
comms  = re.findall('(\d+|L|R)', comm)
# print(comms)

# dirs: 0: right, 1: up, 2: left, 3: down. Turn left: dir+=1, turn right: dir-=1

pos = [0,np.where(A[0,:]>0)[0][0]]
dir = 0
# print(pos)
for c in comms:
    # print('\n')
    if(c == 'L'):
        dir = (dir+1)%4
        # print(f'dir: {dir}')
    elif(c == 'R'):
        dir = (dir-1)%4
        # print(f'dir: {dir}')
    else:
        # print(pos)
        pos = moveAhead(A,pos,dir,int(c))
        # print(pos)  

if(dir ==1):
    dirOut = 3
elif(dir == 3):
    dirOut =1
else: 
    dirOut = dir
print( 1000 * (pos[0]+ 1 ) + 4 * (pos[1] + 1) + dir)

6032


In [71]:
print(comm)

10R5L5R10L4R5L5
