In [121]:
from aocd import get_data

YEAR = 2022
DAY = 8

dat = get_data(day=DAY,year=YEAR)

with open('input/8','w') as f:
    f.write(dat)

f.close()


In [9]:
with open('input/8') as f:
    dat = f.read()

In [122]:
import numpy as np

A = np.array([[int(x) for x in i] for i in dat.split('\n')])
print(A)

[[0 1 2 ... 2 0 2]
 [1 0 2 ... 0 2 1]
 [2 2 2 ... 2 0 1]
 ...
 [0 0 1 ... 0 2 1]
 [2 1 2 ... 2 1 2]
 [1 1 0 ... 0 1 0]]


In [123]:
# Check a side and create boolean map which can be seen
def createSeen(A):
    xSize = np.size(A,0)
    ySize = np.size(A,1)
    lHeight = np.array([-1]*xSize)
    isSeen = A ==-1
    for i in range(ySize):
        isSeen[i] = (A[i] > lHeight)
        lHeight = np.maximum(A[i],lHeight)

    return isSeen

print(createSeen(A))

[[ True  True  True ...  True  True  True]
 [ True False False ... False  True False]
 [ True  True False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]


In [124]:
isSeen = A ==-1
for i in range(4):
    # rotate input i times then rotate output back
    seenMat = np.rot90(createSeen(np.rot90(A,i)),-i)
    isSeen = np.logical_or(isSeen, seenMat)

print(f'Problem 1 Solution: {np.sum(isSeen)}')

Problem 1 Solution: 1825


In [125]:
def calcSeen(v):
    tot =0
    for i in v[-2::-1]:
        if i < v[-1]:
            tot = tot+1
        else:
            return tot+1
    return tot

In [130]:
# Problem 2


xSize = np.size(A,0)
ySize = np.size(A,1)

maxVal = 0

for i in range(1,xSize-1):
    for j in range(1,ySize-1):
        # verticle 2 ways
        s = 1
        s = s* calcSeen(A[0:i+1,j])
        s = s* calcSeen(A[:i-1:-1,j])
        # horizontal
        s = s* calcSeen(A[i,0:j+1])
        s = s* calcSeen(A[i,:j-1:-1])
        maxVal = max([s,maxVal])

print(f'Problem 2: {maxVal}')

Problem 2: 235200
